In [1]:
import numpy as np

# array filed with zeros

In [8]:
arr_zero=np.zeros(4)
print(arr_zero)

[0. 0. 0. 0.]


# array with 1

In [14]:
arr_one=np.ones(4)
arr_one

array([1., 1., 1., 1.])

In [18]:
arr_one=np.ones((4,8))
print(arr_one)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


# array with empty value

In [25]:
arr_empty=np.empty(5)
print(arr_empty)
# walue is gate is row value of memory

[2.12199579e-314 4.67296746e-307 5.07899484e-321 3.79442416e-321
 1.71611676e-317]


# range

In [47]:
arr_range=np.arange(0,10)
print(arr_range)

[0 1 2 3 4 5 6 7 8 9]


# diagonal filed with one

In [52]:
arr_digonal_wiht_1=np.eye(5)
print(arr_digonal_wiht_1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# array element space between them - linspace

In [62]:
arr_space=np.linspace(0,20,5)
print(arr_space)

[ 0.  5. 10. 15. 20.]
