In [1]:
import numpy as np

# random

# rand() -range from 0 to 1

In [9]:
a=np.random.rand(5)
print(a)

[0.07074032 0.99552549 0.94354314 0.44909009 0.47461195]


In [15]:
a=np.random.rand(3,2)
print(a)

[[0.31974194 0.00256256]
 [0.77088228 0.85391554]
 [0.92706217 0.78773359]]


# randn()

In [73]:
# value from 0 to 1
# but i didnt get it into negative value
b=np.random.rand(4)
print(b)


[0.65323027 0.44769724 0.94481098 0.67959775]


# randf()

In [86]:
c=np.random.ranf(3)
print(c)

[0.24002984 0.33364058 0.82237956]


# randint()


In [89]:
# to get range number with range   value  is n integer

In [95]:
# n=np.random.randint(min,max,total_value_we_want)

n=np.random.randint(3,10,4)
print(n)

[9 3 6 4]
