In [5]:
import numpy as np

In [14]:
a=np.array([2,3,4,5,5,6])
print(a)
print(a.ndim)
print(a.shape)

[2 3 4 5 5 6]
1
(6,)


In [18]:
# convert into two dim -  should be have sufficient element
y=a.reshape(2,3)
print(y)
print(y.ndim)

[[2 3 4]
 [5 5 6]]
2


In [30]:
# convert into three dim
arr1=np.array([1,2,3,4,6,7,8,9,10,11,12,5])
arr2=arr1.reshape(2,3,2)
print(arr2)

[[[ 1  2]
  [ 3  4]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12  5]]]


In [34]:
# convert the n dim array into 1 dim
arr3=arr2.reshape(-1)
print(arr3)

[ 1  2  3  4  6  7  8  9 10 11 12  5]
