In [3]:
import numpy as np

In [12]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3])
arr3=np.add(arr1,arr2)
print(arr3)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [14]:
# the above problem we get dute to do not having same number of length of array

In [18]:
# but we can add it by using matring sum like (1,3) and (3,1) can get sum in matrix and make (3,3) matrix

In [24]:
arr1=np.array([1,2,3])
arr2=np.array([[[1],[2],[3]]])
arr3=np.add(arr1,arr2)
print(arr3)

[[[2 3 4]
  [3 4 5]
  [4 5 6]]]


In [38]:
# now (2,1) and (2,2) array
arr1=np.array([[1,3]])
arr2=np.array([[1,2],[1,2]])
arr1.shape
arr3=np.add(arr1,arr2)
print(arr3)

[[2 5]
 [2 5]]


In [40]:
# now (2,1) and (2,2) array
arr1=np.array([[1,3]])
arr2=np.array([[1,2],[1,2]])
arr1.shape
arr3=np.multiply(arr1,arr2)
print(arr3)

[[1 6]
 [1 6]]


In [42]:
arr1=np.array([1,2,3])
arr2=np.array([[[1],[2],[3]]])
arr3=np.multiply(arr1,arr2)
print(arr3)

[[[1 2 3]
  [2 4 6]
  [3 6 9]]]
