In [1]:
import numpy as np

In [3]:
a=np.array([2,3,4,5,6,7,8])
print(a[3])

5


In [5]:
print(a[0])

2


In [7]:
# multidimentional array

In [11]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a[0,3])

4


In [13]:
print(a[1,3])

10


# three dimentional array

In [30]:
a=np.array([[[1,2,3],[5,6,7],[4,8,9]]])
print(a)

[[[1 2 3]
  [5 6 7]
  [4 8 9]]]


In [27]:
print(a[0,1,2])

7


In [32]:
# now sclicing

In [38]:
a=np.array([0,1,2,3,4,5,6,7,8])
print(a[:])
# all value print

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [40]:
a=np.array([0,1,2,3,4,5,6,7,8])
print(a[:7])
# from 0 to 7 print

[0, 1, 2, 3, 4, 5, 6]


In [42]:
a=np.array([0,1,2,3,4,5,6,7,8])
print(a[4:8])
# from 4 to 8

[4, 5, 6, 7]


In [46]:
# from starting to 7
a=np.array([0,1,2,3,4,5,6,7,8])
print(a[:7])

[0, 1, 2, 3, 4, 5, 6]


In [48]:
# from 5 to end
a=np.array([0,1,2,3,4,5,6,7,8])
print(a[5:])

[5, 6, 7, 8]


# two dimentional array

In [54]:
a=np.array([[0,1,2],[3,4,5]])
print(a)

[[0 1 2]
 [3 4 5]]


In [60]:
print(a[0,:2])

[0 1]


# three dimentiona

In [64]:
a=np.array([[[0,1,2],[3,4,5]]])
print(a)

[[[0 1 2]
  [3 4 5]]]


In [66]:
print(a[0,0,0:2])

[0 1]
